Fix/remove not needed template files
linz/oidc-provider pull request #11
Opened 2022-07-08 05:53 UTC by linz-jim

Get the easy ones out of the way. Hopefully I didn't miss anything by removing mutation-testing.yml

2022-07-08 10:15 UTC, l0b0 requested changes

2022-07-08 10:15 UTC, l0b0 commented on README.md
> +# OIDC Provider
Excellent set of changes, but the readme update should probably be a separate PR. Also, you need to run `prettier` on it.

2022-07-08 10:15 UTC, l0b0 commented on README.md
> +It is possible to create more than one role using this stack.
How can you create more than one role? Since we won't need it for the Geostore, if it's possible to simplify the code by removing this feature I'd be in favour of that.

2022-07-08 10:15 UTC, l0b0 commented on README.md
> +- An AWS account to deploy this stack.
"to deploy this stack" seems redundant here.

2022-07-08 10:15 UTC, l0b0 commented on README.md
> +- GitHub repo requiring access to AWS using OIDC. Please specify a branch, event or tag for more granular restrictions. This is needed to prevent untrusted workflows or repositories from requesting a
"requiring access to AWS using OIDC" seems redundant here.

A link to the documentation for how to filter branch etc. would be useful.

2022-07-08 10:15 UTC, l0b0 commented on README.md
> +- AWS role policy. This specifies the level of access GitHub actions has on AWS. It is possible to reference existing AWS managed policy, or create your own custom inline policy for bespoke access.
This might be a nice feature for other projects, but in case of the Geostore it might be unnecessary flexibility. I had expected that the stack would include a static IAM policy which we'd attach to this role independently of any existing policies, for simplicity.

2022-07-08 13:47 UTC, l0b0 requested changes

2022-07-11 02:08 UTC, closed without merging

2022-07-12 09:02 UTC, linz-jim commented on README.md
> +cdk deploy --profile <profile-name>
Updated and provided some clarity in [1ef15b3](https://github.com/linz/oidc-provider/pull/14/commits/1ef15b3a5f992872e7a37871d2ebff031e56ad73)

2022-07-12 09:06 UTC, linz-jim commented on README.md
> +Role policy should specify which AWS resources GitHub actions has access to.
Updated in [8aef08d](https://github.com/linz/oidc-provider/pull/14/commits/8aef08d3e5edb87d669ba40af18471a6f548b99f)

2022-07-12 09:15 UTC, linz-jim commented on README.md
> +- An AWS account to deploy this stack.
Fixed in [8aef08d](https://github.com/linz/oidc-provider/pull/14/commits/8aef08d3e5edb87d669ba40af18471a6f548b99f)

2022-07-12 09:18 UTC, linz-jim commented on README.md
> +- GitHub repo requiring access to AWS using OIDC. Please specify a branch, event or tag for more granular restrictions. This is needed to prevent untrusted workflows or repositories from requesting a
Updated in [8aef08d](https://github.com/linz/oidc-provider/pull/14/commits/8aef08d3e5edb87d669ba40af18471a6f548b99f)

2022-07-12 09:22 UTC, linz-jim commented on README.md
> +- AWS role policy. This specifies the level of access GitHub actions has on AWS. It is possible to reference existing AWS managed policy, or create your own custom inline policy for bespoke access.
Documentation updated in [8aef08d](https://github.com/linz/oidc-provider/pull/14/commits/8aef08d3e5edb87d669ba40af18471a6f548b99f). Changed [infrastructure/oidc_provider_stack.py](https://github.com/linz/oidc-provider/pull/13/files#diff-761f56062312f3dd25b4ada5d761360f8984371a8bd2f8e091a47768064f52a6) only reference managed policy.

2022-07-12 09:23 UTC, linz-jim commented on README.md
> +Please refer to [GitHub Documentation](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#example-subject-claims) for furth
Updated in [8aef08d](https://github.com/linz/oidc-provider/pull/14/commits/8aef08d3e5edb87d669ba40af18471a6f548b99f)

2022-07-12 09:26 UTC, linz-jim commented on .github/workflows/mutation-testing.yml
> -        run: poetry run mutmut junitxml > mutmut.xml
Updated in [934f7c5](https://github.com/linz/oidc-provider/pull/12/commits/934f7c5a701b81c099291be3ce85881a2abcd440)

2022-07-12 09:35 UTC, linz-jim commented on README.md
> +# OIDC Provider
Good idea moving README to a separate PR [fix/update-documentation](https://github.com/linz/oidc-provider/tree/fix/update-documentation). 
`prettier` formatting in [7becdbc](https://github.com/linz/oidc-provider/pull/14/commits/7becdbca2ccca9839e5c71218503973abc68ee26)